import tensorrt as trt

efficientdet_model_dict = {
    'efficientdet_lite0':{
        'MODEL_PATH':'onnx_models/efficientdet_lite0_opt.onnx',
        'ENGINE_PATH_FP32':'trt_models/efficientdet_lite0_fp32.engine',
        'ENGINE_PATH_FP16':'trt_models/efficientdet_lite0_fp16.engine',
        'TARGET_SIZE': 320
    },
    'efficientdet_lite1':{
        'MODEL_PATH':'onnx_models/efficientdet_lite1_opt.onnx',
        'ENGINE_PATH_FP32':'trt_models/efficientdet_lite1_fp32.engine',
        'ENGINE_PATH_FP16':'trt_models/efficientdet_lite1_fp16.engine',
        'DTYPE': trt.uint8,
        'TARGET_SIZE': 384
    },
    'efficientdet_lite2':{
        'MODEL_PATH':'onnx_models/efficientdet_lite2_opt.onnx',
        'ENGINE_PATH_FP32':'trt_models/efficientdet_lite2_fp32.engine',
        'ENGINE_PATH_FP16':'trt_models/efficientdet_lite2_fp16.engine',
        'DTYPE': trt.uint8,
        'TARGET_SIZE': 448
    },
    'efficientdet_lite3':{
        'MODEL_PATH':'onnx_models/efficientdet_lite3_opt.onnx',
        'ENGINE_PATH_FP32':'trt_models/efficientdet_lite3_fp32.engine',
        'ENGINE_PATH_FP16':'trt_models/efficientdet_lite3_fp16.engine',
        'TARGET_SIZE': 512
    },
    'efficientdet_lite4':{
        'MODEL_PATH':'onnx_models/efficientdet_lite4_opt.onnx',
        'ENGINE_PATH_FP32':'trt_models/efficientdet_lite4_fp32.engine',
        'ENGINE_PATH_FP16':'trt_models/efficientdet_lite4_fp16.engine',
        'TARGET_SIZE': 640
    }

}

LABELS = [
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bus',
    'train',
    'truck',
    'boat',
    'traffic light',
    'fire hydrant',
    'stop sign',
    'parking meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'backpack',
    'umbrella',
    'handbag',
    'tie',
    'suitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports ball',
    'kite',
    'baseball bat',
    'baseball glove',
    'skateboard',
    'surfboard',
    'tennis racket',
    'bottle',
    'wine glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot dog',
    'pizza',
    'donut',
    'cake',
    'chair',
    'couch',
    'potted plant',
    'bed',
    'dining table',
    'toilet',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrush'
]

